version: "3.9"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    ports:
      - "${HOST_MONGODB_PORT:-27017}:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
