services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "${HOST_MONGODB_PORT:-27017}:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      default:
        aliases:
          - mongo
    healthcheck:
      test: ["CMD-SHELL", "mongosh --quiet --eval 'db.runCommand({ ping: 1 })' >/dev/null 2>&1 || exit 1"]
      interval: 2s
      timeout: 2s
      retries: 6
      start_period: 2s

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_BASICAUTH=false
    ports:
      - "${HOST_MONGO_EXPRESS_PORT:-8081}:8081"

volumes:
  mongodb_data:
